#namespace: trustyai-service-operator-system

namePrefix: trustyai-service-operator-

resources:
- ../crd
- ../rbac
- ../manager

patchesStrategicMerge:
- manager_auth_proxy_patch.yaml

configMapGenerator:
  - name: config
    env: params.env
generatorOptions:
  disableNameSuffixHash: true

vars:
  - name: trustyaiServiceImageName
    objref:
      kind: ConfigMap
      name: config
      apiVersion: v1
    fieldref:
      fieldpath: data.trustyaiServiceImageName
  - name: trustyaiServiceImageTag
    objref:
      kind: ConfigMap
      name: config
      apiVersion: v1
    fieldref:
      fieldpath: data.trustyaiServiceImageTag